CREATE DATABASE IF NOT EXISTS mattermost;

CREATE USER 'mmuser'@'%' IDENTIFIED BY 'MATTERMOST_PASSWORD';
GRANT ALTER, CREATE, DELETE, DROP, INDEX, INSERT, SELECT, UPDATE ON `mattermost`.* TO 'mmuser'@'%';

FLUSH PRIVILEGES;